#!/bin/bash

# remove comma comments and add double newlines between input files

pattern_start='^ *(,,|!!|\.\.\.)'

sub_inline='s/,,.*$//;s/^\s*\?\?\s*//'

# iterate over all positional arguments
for i in "$@"
do
    grep -E --invert-match "$pattern_start" "$i"
    echo
    echo
done | sed -r "$sub_inline"
